CREATE DEFINER=`root`@`localhost` PROCEDURE `MaxProductPerDayLastWeek`(IN locCode VARCHAR(5))
BEGIN
	-- get all max prodcut sold per day for the last week
	-- call MaxProductPerDayLastWeekCTemp(locCode);
    CREATE TEMPORARY TABLE IF NOT EXISTS  MaxProductPerDayLastWeek2(
		DOP DATE, PROD_CODE VARCHAR(5), SALE_ID VARCHAR(5), TOT_UNITS INT
    );
    CREATE TEMPORARY TABLE IF NOT EXISTS  MaxProductPerDayLastWeek3(
		DOP12 DATE, TOT_UNITS12 INT
    );
    TRUNCATE TABLE MaxProductPerDayLastWeek2;
    TRUNCATE TABLE MaxProductPerDayLastWeek3;
    
    INSERT INTO MaxProductPerDayLastWeek2 SELECT DOP, PROD_CODE, SALE_ID,sum(NOU) AS TOT_UNITS
	FROM (SELECT S.DOP,S.SALE_ID,SP.PROD_CODE,SP.NOU FROM LAST_WEEK_SALES S, SALE_PRODUCT SP WHERE S.SALE_ID=SP.SALE_ID AND LOC_CODE=locCode) AS RES1 
    GROUP BY DOP, PROD_CODE ORDER BY DOP;
    
	INSERT INTO MaxProductPerDayLastWeek3 SELECT RES2.DOP AS DOP12, MAX(RES2.TOT_UNITS) AS TOT_UNITS12 
    FROM MaxProductPerDayLastWeek2 AS RES2 
	GROUP BY RES2.DOP;
    
    SELECT DOP, TOT_UNITS, P.PROD_CODE, P.PROD_NAME FROM MaxProductPerDayLastWeek2 AS RES2
	INNER JOIN MaxProductPerDayLastWeek3 AS RES3
	ON RES3.DOP12=DOP AND RES3.TOT_UNITS12=TOT_UNITS
	,
	PRODUCT P
	WHERE P.PROD_CODE=RES2.PROD_CODE;
END