-- Create tables with primary key and some check constraints
--      check contraint checks whether the gender is in either of the 3 mentioned type
CREATE TABLE PRODUCT(
    PROD_CODE VARCHAR(5) PRIMARY KEY,
    PROD_NAME VARCHAR(15),
    CAT_CODE VARCHAR(5)
);

CREATE TABLE CATEGORY(
    CAT_CODE VARCHAR(5) PRIMARY KEY,
    CAT_NAME VARCHAR(15)
);

CREATE TABLE CUSTOMER(
    CUST_ID VARCHAR(5) PRIMARY KEY,
    CUST_NAME VARCHAR(20),
    CUST_DOB DATE,
    CUST_GENDER CHAR(1),
    CUST_MOBILE VARCHAR(10),
    LOC_CODE VARCHAR(5),
    CONSTRAINT CHECK_CUSTOMER_GENDER CHECK(CUST_GENDER IN ('M','F','O'))
);

CREATE TABLE SALES_EXE(
    SE_ID VARCHAR(5) PRIMARY KEY,
    SE_NAME VARCHAR(20),
    SE_DOB DATE,
    SE_GENDER CHAR(1),
    SE_MOBILE VARCHAR(10),
    CONSTRAINT CHECK_SE_GENDER CHECK(SE_GENDER IN('M','F','O'))
);

CREATE TABLE LOCATION(
    LOC_CODE VARCHAR(5) PRIMARY KEY,
    LOC_NAME VARCHAR(15)
);

CREATE TABLE SALES(
    SE_ID VARCHAR(5),
    CUST_ID VARCHAR(5),
    PROD_CODE VARCHAR(5),
    DOP DATE,
    NOU INT,
    PRIMARY KEY(SE_ID, CUST_ID, PROD_CODE, DOP)
);

-- Updating Foreign keys to the tables
ALTER TABLE PRODUCT ADD FOREIGN KEY (CAT_CODE) REFERENCES CATEGORY(CAT_CODE);

ALTER TABLE CUSTOMER ADD FOREIGN KEY (LOC_CODE) REFERENCES LOCATION(LOC_CODE);

ALTER TABLE SALES ADD FOREIGN KEY (SE_ID), REFERENCES SALES_EXE(SE_ID);
ALTER TABLE SALES ADD FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID);
ALTER TABLE SALES ADD FOREIGN KEY (PROD_CODE) REFERENCES PRODUCT(PROD_CODE);